# Generated by Django 5.0.4 on 2024-04-20 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Code')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('syllabus', models.FileField(upload_to='syllabus/', verbose_name='Syllabus')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['code', 'title'],
                'indexes': [models.Index(fields=['title'], name='course_title_idx')],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Name')),
                ('courses', models.ManyToManyField(related_name='faculties', to='academic_portal.course', verbose_name='Courses')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('courses', models.ManyToManyField(related_name='lecturers', to='academic_portal.course', verbose_name='Courses')),
            ],
            options={
                'verbose_name': 'Lecturer',
                'verbose_name_plural': 'Lecturers',
                'ordering': ['last_name', 'first_name', 'date_of_birth', 'email'],
                'indexes': [models.Index(fields=['first_name'], name='lecturer_first_name_idx'), models.Index(fields=['last_name'], name='lecturer_last_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('year_of_study', models.PositiveSmallIntegerField(choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], verbose_name='Year of Study')),
                ('courses', models.ManyToManyField(related_name='students', to='academic_portal.course', verbose_name='Courses')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academic_portal.faculty', verbose_name='Faculty')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['last_name', 'first_name', 'date_of_birth', 'email', 'year_of_study', 'faculty'],
                'indexes': [models.Index(fields=['last_name'], name='student_last_name_idx')],
            },
        ),
    ]
