# Generated by Django 5.0.4 on 2024-04-25 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_portal', '0002_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academic_portal.course', verbose_name='Course'),
        ),
    ]
