# Generated by Django 5.0.4 on 2024-04-29 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_portal', '0004_auto_20240428_1723'),
        ('academic_portal', '0005_alter_assignment_course'),
    ]

    operations = [
    ]
